#...................................................................
#: Kua: Launcher : Copyright (C) 2022 sOkam! : GNU GPLv3 or higher :
#...................................................................

import ./deps
import ./cfg
#................................
# State
#................................
var mousePos  *:Vector2=  (0, 0)
var wPos      *:Vector2=  (0, 0)
var panOffset *:Vector2=  mousePos
var wDrag     *:bool=     false
var wExit     *:bool=     false
var wWidth    *:float=    wRes.x * wScale
var wHeight   *:float=    wRes.y * wScale
#................................
type State * = enum
  None, ChkDownload, Download, Update, Launch
#................................
var state *:State= State.Launch
#................................
