#...................................................................
#: Kua: Launcher : Copyright (C) 2022 sOkam! : GNU GPLv3 or higher :
#...................................................................

import ./backend/core as backend

#......................
proc run()=
  echo "Backend: Finished"
  quit(0)
#......................
when isMainModule: run()
